UpAssist.Neos.ReCaptcha:Mixin.ReCaptchaConfiguration:
  abstract: true
  ui:
    label: i18n
    inspector:
      groups:
        recaptcha:
          label: i18n
          icon: 'fas fa-user-shield'
  properties:
    recaptchaSiteKey:
      type: string
      ui:
        label: i18n
        inspector:
          group: recaptcha
      validation:
        Neos.Neos/Validation/NotEmptyValidator: { }
    recaptchaSecret:
      type: string
      ui:
        label: i18n
        inspector:
          group: recaptcha
      validation:
        Neos.Neos/Validation/NotEmptyValidator: { }
